FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir && rm requirements*.txt
COPY . .

CMD ["uvicorn", "transport.app_sleep:app", "--host", "0.0.0.0", "--port", "8000"]
