apiVersion: v1
kind: Pod
metadata:
  name: heart-desease-server-resources
  labels:
    app: heart-desease-server
spec:
  containers:
    - image: pythondestroyer/heart_desease_server:v2
      name: heart-desease-server
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Gi"
          cpu: "1"