apiVersion: v1
kind: Pod
metadata:
  name: heart-desease-server-probes
  labels:
    app: heart-desease-server-probes
spec:
  containers:
    - image: pythondestroyer/online_inference:v3
      name: heart-desease-server-probes
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Gi"
          cpu: "1"
      livenessProbe:
        httpGet:
          path: /healthcheck
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /healthcheck
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10