_target_: ml_project.preprocessing.data_transformer.DefaultTransformer
categorial: ["age", "sex", "fbs", "restecg", "exang", "slope", "ca", "thal"]
numerical: ["cp", "trestbps", "chol", "thalach", "oldpeak"]