defaults:
  - _self_
  - model: logreg
  - metric: f1_score
  - dataset: heart
  - preprocessing: default
  - general: default
  - inference: default
  - logger: mlflow
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  run:
    dir: ${general.artifacts_dir}/${general.run_name}
  sweep:
    dir: ${general.artifacts_dir}/${general.run_name}
    subdir: ${hydra.job.override_dirname}
