defaults:
  - _self_
  - model: logreg
  - metric: f1_score
  - dataset: heart
  - preprocessing: default
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  seed: 42
  checkpoint_path: weights
  project_dir: ${hydra:runtime.cwd}

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
